### PR TITLE
Move to platform debug (rename the packages to be org.eclipse.debug.unittest.*)

### PR DESCRIPTION
**Pull request by vrubezhny**

### CODE REVIEW

**Comment by akurtakov** [comment]
I have my doubts here. Actually I think I like org.eclipse.unittest better as it doesn't have much to share with debug. 
JUnit and CDT definetely shouldn't be in o.e.debug namespace as they are not going there for sure. 
I would encourage you to get more people opinion on the topic before proceeding.

**Comment by akurtakov** [comment]
By more people maybe even ask for comment on platform-dev?

**Comment by vrubezhny** [comment]
@akurtakov so, you agree with @mickaelistria  in that we actually don't need to do such renaming at all?

**Comment by akurtakov** [comment]
I think we should target Platform debug but this doesn't mean it has to be starting with org.eclipse.debug. There are bundles with different name pattern in this repo.

**Comment by vrubezhny** [comment]
Closing the PR as not needed

**Comment by vogella** [comment]
+1, I don't think a rename it necessary.

**Pull request closed without merging**
